### ISSUE TITLE
can't use cto

### ISSUE THREAD

**Issue by Flyour** [herosi/CTO#1]
- Error:
Failed while executing plugin_t.run():
Traceback (most recent call last):
  File "C:/Program Files/IDA Pro 7.5 SP3/plugins/cto_plugin.py", line 153, in run
    self.exec_cto()
  File "C:/Program Files/IDA Pro 7.5 SP3/plugins/cto_plugin.py", line 126, in exec_cto
    self.g = cto.exec_cto(cto_data=sync_data, debug=debug)
  File "C:\Program Files\IDA Pro 7.5 SP3\plugins\cto\cto.py", line 4058, in exec_cto
    return cto
UnboundLocalError: local variable 'cto' referenced before assignment

- Log:
Launching CTO (Call Tree Overviewer) ...
For the first execution, CTO will analyze all functions to build the call tree. Please wait for a while.
data is unavailable. extract data from idb or pickle
Got a unexpected error (<class 'IndexError'>: pop from empty list) (4049)
Traceback (most recent call last):
  File "C:\Program Files\IDA Pro 7.5 SP3\plugins\cto\cto.py", line 4049, in exec_cto
    cto = CallTreeOverviewer(ida_kernwin.get_screen_ea(), cto_data=cto_data , debug=debug)
  File "C:\Program Files\IDA Pro 7.5 SP3\plugins\cto\cto.py", line 99, in __init__
    cto_base.cto_base.__init__(self, cto_data, debug)
  File "C:\Program Files\IDA Pro 7.5 SP3\plugins\cto\cto_base.py", line 80, in __init__
    self.update_data()
  File "C:\Program Files\IDA Pro 7.5 SP3\plugins\cto\cto_base.py", line 223, in update_data
    self.cache_update()
  File "C:\Program Files\IDA Pro 7.5 SP3\plugins\cto\cto_base.py", line 153, in cache_update
    self.cto_data["cto_data"]["func_relations"], self.cto_data["cto_data"]["import_eas"], self.cto_data["cto_data"]["string_eas"] = get_func_relation.get_func_relations()
  File "C:\Program Files\IDA Pro 7.5 SP3\plugins\cto\get_func_relation.py", line 875, in get_func_relations
    for func_ea, parents, children, func_type, gvars, strings, stroff, vtbl in get_relation_in_all_funcs(import_eas, string_eas):
  File "C:\Program Files\IDA Pro 7.5 SP3\plugins\cto\get_func_relation.py", line 866, in get_relation_in_all_funcs
    for ea, parents, children, func_type, gvars, strings, stroff, vtbl in get_func_relation(f, import_eas, string_eas):
  File "C:\Program Files\IDA Pro 7.5 SP3\plugins\cto\get_func_relation.py", line 848, in get_func_relation
    parents, children, apicalls, gvars, strings, stroff, vtbl = get_family_members(f.start_ea, bbs, import_eas, string_eas)
  File "C:\Program Files\IDA Pro 7.5 SP3\plugins\cto\get_func_relation.py", line 838, in get_family_members
    children, apicalls, gvars, strings, stroff, vtbl = get_children(bbs, import_eas, string_eas)
  File "C:\Program Files\IDA Pro 7.5 SP3\plugins\cto\get_func_relation.py", line 684, in get_children
    get_calls_in_bb(bb, bbs, import_eas, string_eas, result=result, apicalls=apicalls, gvars=gvars, strings=strings, stroff=stroff, vtbl=vtbl)
  File "C:\Program Files\IDA Pro 7.5 SP3\plugins\cto\get_func_relation.py", line 655, in get_calls_in_bb
    target_ea, func_type, op, target_name = get_funcptr_ea(ea, bbs, import_eas, string_eas)
  File "C:\Program Files\IDA Pro 7.5 SP3\plugins\cto\get_func_relation.py", line 509, in get_funcptr_ea
    tmp_func_name, tmp_func_type, _v = get_func_info_by_opstr(ea, i)
  File "C:\Program Files\IDA Pro 7.5 SP3\plugins\cto\get_func_relation.py", line 261, in get_func_info_by_opstr
    member_name = member_names.pop()
IndexError: pop from empty list

- IDA Version 7.5 sp3
- python  3.9.0

**Comment by herosi** [comment]
What binary architecture do you analyze? Please provide the idb if you can.
