### ISSUE TITLE
AttributeError: module 'comments' has no attribute 'comment_t"

### ISSUE THREAD

**Issue by maskelihileci** [herosi/CTO#7]
Failed while executing plugin_t.run():
Traceback (most recent call last):
  File "C:/IDA Pro 7.7 SP1/plugins/cto_func_lister_plugin.py", line 149, in run
    self.exec_cto_func_lister()
  File "C:/IDA Pro 7.7 SP1/plugins/cto_func_lister_plugin.py", line 118, in exec_cto_func_lister
    self.g = cto_func_lister.exec_cto_function_lister(cto_data=sync_data, debug=debug)
  File "C:\IDA Pro 7.7 SP1\plugins\cto\cto_func_lister.py", line 1715, in exec_cto_function_lister
    cto_func_lister = cto_func_lister_t(cto_data=cto_data, debug=debug)
  File "C:\IDA Pro 7.7 SP1\plugins\cto\cto_func_lister.py", line 535, in __init__
    cto_base.cto_base.__init__(self, cto_data, curr_view, debug)
  File "C:\IDA Pro 7.7 SP1\plugins\cto\cto_base.py", line 62, in __init__
    self.cmt_obj = comments.comment_t()
AttributeError: module 'comments' has no attribute 'comment_t'

I'm going crazy. I tried to solve it myself, everything seems correct, but I keep getting this error.

IDA PRO 7.7
Windows 10
Python 3.8

**Comment by maskelihileci** [comment]
"It happens when I click on the CTO Function Lister, by the way.

**Comment by herosi** [comment]
This might occur because you have another comments.py or comments folder in your python path or in your IDA related folders and you have already imported it before loading comments.py in CTO. Remove or rename them first.
