### ISSUE TITLE
 KeyError: 42248388 plugins cto_func_lister.py  line 1576, in count_func_type

### ISSUE THREAD

**Issue by zengfr** [herosi/CTO#8]
2023-11-05 22:03:19.182 IDAPython: Error while calling Python callback <OnCreate>:
2023-11-05 22:03:19.182 Traceback (most recent call last):
2023-11-05 22:03:19.182   File "D:\soft\IDA_Pro_7.7\plugins\cto\cto_func_lister.py", line 1370, in OnCreate
2023-11-05 22:03:19.182     self.create_tree()
2023-11-05 22:03:19.182   File "D:\soft\IDA_Pro_7.7\plugins\cto\cto_func_lister.py", line 1386, in create_tree
2023-11-05 22:03:19.182     self.PopulateTree()
2023-11-05 22:03:19.182   File "D:\soft\IDA_Pro_7.7\plugins\cto\cto_func_lister.py", line 1664, in PopulateTree
2023-11-05 22:03:19.182     func_name, ifunc, idx = self.RegisterFuncToTree(imp_dll, imp_ea, imp_name, self.imports, self.imports_ids, other_data=(imp_name, imp_ord, dll_name))
2023-11-05 22:03:19.182   File "D:\soft\IDA_Pro_7.7\plugins\cto\cto_func_lister.py", line 1591, in RegisterFuncToTree
2023-11-05 22:03:19.182     ifunc_internal_funcs_cnt.setData(self.count_func_type(func_ea, [FT_GEN]), QtCore.Qt.DisplayRole)
2023-11-05 22:03:19.182   File "D:\soft\IDA_Pro_7.7\plugins\cto\cto_func_lister.py", line 1576, in count_func_type
2023-11-05 22:03:19.182     r = [d for k,(d,ft,_,_) in self.func_relations[func_ea]['children'].items() if ft in func_types]
2023-11-05 22:03:19.182 KeyError: 42248388
2023-11-05 22:03:20.747

**Comment by zengfr** [comment]
2023-11-05 22:56:59.385 Traceback (most recent call last):
2023-11-05 22:56:59.385   File "D:\soft\IDA_Pro_7.7\plugins\cto\cto.py", line 2092, in OnDblClick
2023-11-05 22:56:59.385     r = self._expand_collapse_node(node_id)
2023-11-05 22:56:59.385   File "D:\soft\IDA_Pro_7.7\plugins\cto\cto.py", line 2051, in _expand_collapse_node
2023-11-05 22:56:59.385     refresh_flag = self.filter_nodes(node_id)
2023-11-05 22:56:59.385   File "D:\soft\IDA_Pro_7.7\plugins\cto\cto.py", line 1827, in filter_nodes
2023-11-05 22:56:59.385     for p in self.find_path(self.nodes[ea], end_nid=-1, direction=tmp_direction, nodes_limitation=set([self.nodes[x] for x in self.related_nodes[ea]])):
2023-11-05 22:56:59.385   File "D:\soft\IDA_Pro_7.7\plugins\cto\cto.py", line 1827, in <listcomp>
2023-11-05 22:56:59.385     for p in self.find_path(self.nodes[ea], end_nid=-1, direction=tmp_direction, nodes_limitation=set([self.nodes[x] for x in self.related_nodes[ea]])):
2023-11-05 22:56:59.385 KeyError: 13976195

**Comment by zengfr** [comment]
2023-11-05 23:06:38.552 get data from global variable
2023-11-05 23:09:15.136 IDAPython: Error while calling Python callback <OnCreate>:
2023-11-05 23:09:15.136 Traceback (most recent call last):
2023-11-05 23:09:15.136   File "D:\soft\IDA_Pro_7.7\plugins\cto\cto_func_lister.py", line 1370, in OnCreate
2023-11-05 23:09:15.136     self.create_tree()
2023-11-05 23:09:15.136   File "D:\soft\IDA_Pro_7.7\plugins\cto\cto_func_lister.py", line 1386, in create_tree
2023-11-05 23:09:15.136     self.PopulateTree()
2023-11-05 23:09:15.136   File "D:\soft\IDA_Pro_7.7\plugins\cto\cto_func_lister.py", line 1664, in PopulateTree
2023-11-05 23:09:15.136     func_name, ifunc, idx = self.RegisterFuncToTree(imp_dll, imp_ea, imp_name, self.imports, self.imports_ids, other_data=(imp_name, imp_ord, dll_name))
2023-11-05 23:09:15.136   File "D:\soft\IDA_Pro_7.7\plugins\cto\cto_func_lister.py", line 1591, in RegisterFuncToTree
2023-11-05 23:09:15.136     ifunc_internal_funcs_cnt.setData(self.count_func_type(func_ea, [FT_GEN]), QtCore.Qt.DisplayRole)
2023-11-05 23:09:15.136   File "D:\soft\IDA_Pro_7.7\plugins\cto\cto_func_lister.py", line 1576, in count_func_type
2023-11-05 23:09:15.136     r = [d for k,(d,ft,_,_) in self.func_relations[func_ea]['children'].items() if ft in func_types]
2023-11-05 23:09:15.136 KeyError: 34219952
2023-11-05 23:09:15.403

**Comment by herosi** [comment]
Although there are some KeyError exceptions, the main reason for these is the CTO's cache is too old. When you launched CTO or CTO function lister for the first time, those addresses (0x20A27B0, 0xD54283 and 0x284A8C4) were defined as functions. However, I think you undefined them manually at some points. Therefore, CTO cannot find the addresses as functions. To fix this, click somewhere on the CTO / CTO Function Lister window and press "F" to regenerate the cache manually.
Although I catch the undefined event or some other events as much as possible, IDA does not issue any events in certain situations (E.g. manipulated from plugins). Although I can avoid these exceptions, you still have to refresh the CTO's cache in certain conditions.
